import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  analytics,
  cardBalance,
  cardUser,
  invoiceTable,
  recentTx,
}: Readonly<{
  analytics: React.ReactNode;
  cardBalance: React.ReactNode;
  cardUser: React.ReactNode;
  invoiceTable: React.ReactNode;
  recentTx: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex-1 flex flex-col overflow-hidden">
          <div className="flex-1 overflow-auto">
            <div className="p-4 sm:p-6 space-y-6">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-1">{cardUser}</div>
                <div className="lg:col-span-1">{cardBalance}</div>
                <div className="lg:col-span-1">{analytics}</div>
              </div>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div>{recentTx}</div>
                <div className="w-full lg:w-auto order-2 lg:order-1">
                  {invoiceTable}
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
